### ISSUE TITLE
Not sure I can trust this

### ISSUE THREAD

**Issue by yjsoon** [jiachenyee/fivepm.xyz#1]
It's not using any modern framework

Pls fix

**Comment by xenosf** [comment]
I can do it in React if you want

**Comment by yjsoon** [comment]
Aurelius framework or bust https://aurelia.io/

**Comment by jiachenyee** [comment]
we added ar
https://github.com/jiachenyee/fivepm.xyz/commit/160c39786106b43dbac7c8104fae5c760020ff9d

**Comment by yjsoon** [comment]
Acceptable
